version: "3.8"
services:
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
    volumes:
      - ./api/data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3030:3030
    volumes:
      - ./backend/src:/app/src
      - ./backend/node_modules:/app/node_modules
    depends_on:
      - mongodb
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - ./frontend/node_modules:/app/node_modules
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend
